"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Box, CssBaseline, Paper, ThemeProvider, createTheme } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = createTheme({
    palette: {
      // mode: "dark",
    },
  });
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <Box sx={{
              backgroundColor:theme.palette.background.default,
              height:"100vh"
            }}>
              <CssBaseline/>
            {children}
            </Box>
            </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
